version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./docker/db/db-access.env

  app:
    build: ./docker/app
    container_name: django
    expose:
      - "8080"
    volumes:
      - ./docker/app:/project
    depends_on:
      - db
    command: uwsgi --ini /project/uwsgi.ini

  web:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./docker/app:/project
    depends_on:
      - app

volumes:
    db-data: